[project]
name = "hala"
authors = [{ name = "Hala", email = "admin@example.com" }]
description = "Modern ERPNext business portal for Hala Shop"
requires-python = ">=3.14"
readme = "README.md"
dynamic = ["version"]
dependencies = []

[tool.bench.frappe-dependencies]
frappe = ">=16.0.0-dev,<17.0.0"
erpnext = ">=16.0.0-dev,<17.0.0"

[build-system]
requires = ["flit_core >=3.4,<4"]
build-backend = "flit_core.buildapi"

[tool.ruff]
line-length = 110
target-version = "py314"

[tool.ruff.format]
quote-style = "double"
indent-style = "tab"

